/**
 * Example: Imports Diviner with Divination Engine 🌀
 * 
 * Demonstrates round-based lazy computation for import generation.
 * 
 * This mirrors spire-loom's imports diviner but with discovered rounds
 * and mejs template integration.
 */

import {
  createDivination,
  source,
  transform,
  quotable,
  Stub
} from './divination-engine.js';
import { renderWithDivination, createQuotableContext } from './mejs-integration.js';

// ============================================================================
// Domain Types
// ============================================================================

interface Method {
  name: string;
  returnType: Type;
  parameters: Parameter[];
}

interface Type {
  name: string;
  isEntity: boolean;
  importPath?: string;
}

interface Parameter {
  name: string;
  type: Type;
}

interface ImportEntry {
  name: string;
  path: string;
  isEntity: boolean;
  sourceMethod: string;
}

// ============================================================================
// Mock Language Definition (Simulating spire-loom's two-layer architecture)
// ============================================================================

const mockLanguage = {
  name: 'typescript',
  codeGen: {
    rendering: {
      renderImportStatement(importSpec: string, modulePath: string): string {
        return `import ${importSpec} from "${modulePath}";`;
      }
    }
  }
};

// ============================================================================
// The Imports Divination
// ============================================================================

/**
 * Create a divination for imports from a set of methods.
 * 
 * Round 1: Collect all return types that are entities
 * Round 2: Deduplicate by name
 * Round 3: Group by path
 * Round 4: Render import statements
 */
export function createImportsDivination(methods: Method[]) {
  return createDivination(({ source, transform, quotable }) => {
    // Round 1: Source stubs for each method's return type
    // These materialize immediately (no dependencies) when we scan methods
    const entityReturns = methods
      .filter(m => m.returnType.isEntity)
      .map(m => source<ImportEntry>(
        `method.${m.name}.returnType`,
        [], // No dependencies - ripe immediately
        () => ({
          name: m.returnType.name,
          path: `./entities/${m.returnType.name}`,
          isEntity: true,
          sourceMethod: m.name
        })
      ));

    // Round 2: Transform - collect and deduplicate
    // Depends on all entityReturns
    const uniqueEntries = transform<ImportEntry[], typeof entityReturns>(
      entityReturns,
      (...entries) => {
        // Deduplicate by name
        const seen = new Set<string>();
        return entries.filter(e => {
          if (seen.has(e.name)) return false;
          seen.add(e.name);
          return true;
        });
      }
    );

    // Round 3: Transform - group by path for consolidated imports
    const grouped = transform<
      Array<{ path: string; names: string[] }>,
      [typeof uniqueEntries]
    >(
      [uniqueEntries],
      (entries) => {
        const byPath = new Map<string, string[]>();
        for (const e of entries) {
          const existing = byPath.get(e.path) || [];
          existing.push(e.name);
          byPath.set(e.path, existing);
        }
        return Array.from(byPath.entries()).map(([path, names]) => ({
          path,
          names
        }));
      }
    );

    // Round 4: Transform - render import statements
    const rendered = transform<string, [typeof grouped]>(
      [grouped],
      (groups) => {
        const renderImport = mockLanguage.codeGen.rendering.renderImportStatement;
        return groups
          .map(g => renderImport(`{ ${g.names.join(', ')} }`, g.path))
          .join('\n');
      }
    );

    // Make it quotable for template integration
    // The quotable stub's toString() returns {{...}} placeholder during Phase 1
    return quotable(rendered, 1);
  });
}

// ============================================================================
// Usage with mejs Templates
// ============================================================================

const EXAMPLE_TEMPLATE = `
//! Generated TypeScript File
//! This file is auto-generated by the Divination Engine

{{ imports }}

// Method signatures
{% for method in methods %}
function {{ method.name }}(): {{ method.returnType.name }} {
  // Implementation
}
{% endfor %}
`;

export async function demoImportsDivination() {
  // Mock methods
  const methods: Method[] = [
    {
      name: 'createBookmark',
      returnType: { name: 'Bookmark', isEntity: true },
      parameters: [{ name: 'url', type: { name: 'string', isEntity: false } }]
    },
    {
      name: 'getUser',
      returnType: { name: 'User', isEntity: true },
      parameters: []
    },
    {
      name: 'updateBookmark',
      returnType: { name: 'Bookmark', isEntity: true }, // Duplicate!
      parameters: []
    },
    {
      name: 'deleteBookmark',
      returnType: { name: 'void', isEntity: false },
      parameters: []
    }
  ];

  console.log('🌀 Creating imports divination...');
  const importsDiv = createImportsDivination(methods);

  console.log('📊 Discovered stubs:');
  for (const [id, stub] of importsDiv.stubs) {
    console.log(`  ${stub._tag}: ${id}`);
  }

  // Method 1: Direct resolution (no templates)
  console.log('\n🔮 Direct resolution:');
  const directResult = await importsDiv.resolve();
  console.log(directResult);

  // Method 2: Template integration with quoting
  console.log('\n📝 Template rendering with divination:');
  
  const context = createQuotableContext({
    imports: importsDiv.root,
    methods
  });

  // Watch rounds
  console.log('\n📈 Watching solver rounds:');
  for await (const round of importsDiv.watch()) {
    console.log(`  Round ${round.round}: ${round.materialized.size} stubs resolved`);
  }

  // Full template render
  console.log('\n✨ Final rendered template:');
  const rendered = await renderWithDivination({
    template: EXAMPLE_TEMPLATE,
    context: { imports: importsDiv.root, methods },
    maxPasses: 5
  });
  console.log(rendered);

  return rendered;
}

// ============================================================================
// Nested Divination Example
// ============================================================================

/**
 * Demonstrates the fractal nature: a divination that depends on another divination.
 */
export function createNestedDivination() {
  return createDivination(({ source, transform, quotable }) => {
    // Round 1: Get user ID (needs session)
    const sessionUserId = source<string>(
      'auth.session.userId',
      [],
      () => 'user_123' // In real code: auth.getSession().userId
    );

    // Round 2: User details divination (depends on userId)
    const userDetails = transform<
      { id: string; name: string },
      [typeof sessionUserId]
    >(
      [sessionUserId],
      (userId) => ({ id: userId, name: `User_${userId}` })
    );

    // Round 3: Dashboard divination (nested, depends on user)
    const dashboard = transform<
      { user: any; postCount: number },
      [typeof userDetails]
    >(
      [userDetails],
      (user) => ({
        user,
        postCount: 42 // Would query DB in real code
      })
    );

    return quotable(dashboard, 1);
  });
}

// Run demo if executed directly
if (import.meta.url === `file://${process.argv[1]}`) {
  demoImportsDivination().catch(console.error);
}
