# Generated by Django 6.0.2 on 2026-02-23 13:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Worker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(unique=True)),
                ("capacity", models.JSONField(default=dict)),
                ("last_seen", models.DateTimeField(default=django.utils.timezone.now)),
                ("task_types", models.JSONField(default=list)),
                ("is_self", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-last_seen"],
            },
        ),
    ]
