/**
 * APP Generator Engine
 * 
 * Generates complete APP packages from templates.
 */

import * as fs from "fs/promises";
import * as path from "path";

import { generateApp } from "./templates.js";
import type { AppGenerationConfig, AppPackage } from "./types.js";

/**
 * Render APP to markdown files.
 */
function renderAppToFiles(app: AppPackage): Record<string, string> {
  const files: Record<string, string> = {};
  
  /* APP.md - The execution plan */
  files["APP.md"] = `# ${app.metadata.name}: Action Plan Package (APP)

> *"${app.readme.originStory}"*

${app.metadata.isMeta ? `> **META-NOTE**: ${app.readme.metaNote}\n` : ""}

## Before You Start - The Ritual

**STOP. DO THIS FIRST.**

1. **Invoke the required skills** - Always re-ground in context
2. **Read this entire plan** before writing any code
3. **Check off steps as you complete them** - conserve your own progress

**Required Skills:**
${app.skills.map(s => `- \`${s.skill}\`: ${s.purpose}`).join("\n")}

---

## Execution Plan

${app.execution.phases.map(phase => `
### ${phase.name}

${phase.description}

**Estimated Time:** ${phase.estimatedMinutes} minutes

**Steps:**
${phase.steps.map(s => `- [${s.completed ? "x" : " "}] ${s.description}`).join("\n")}

**Checkpoints:**
${phase.checkpoints.map(c => `- [ ] ${c}`).join("\n")}
`).join("\n---\n")}

---

## Completion Checklist

- [ ] All phases complete
- [ ] Build succeeds
- [ ] Tests pass
- [ ] Documentation complete
- [ ] **Even this outdoing has been conserved** ✨

---

*Generated by kimprint - ${app.metadata.createdAt.toISOString()}*
`;

  /* ARCHITECTURE.md */
  files["ARCHITECTURE.md"] = `# ${app.metadata.name}: Architecture

> *"The architecture IS the argument."*

## Overview

${app.architecture.overview}

## Design Patterns

${app.architecture.patterns.map(p => `
### ${p.name}

${p.description}

**Rationale:** ${p.rationale}
`).join("\n")}

## Extension Points

${app.architecture.extensionPoints.map(e => `- ${e}`).join("\n")}

---

*The spiral conserves what matters.*
`;

  /* FAILURE_MODES.md */
  files["FAILURE_MODES.md"] = `# ${app.metadata.name}: Failure Modes

> *"Solarpunk needs to be resilient, not just optimistic."*

## Risk Assessment

| Scenario | Probability | Impact | Mitigation |
|----------|-------------|--------|------------|
${app.failureModes.risks.map(r => `| ${r.scenario} | ${r.probability} | ${r.impact} | ${r.mitigation} |`).join("\n")}

---

*The spiral conserves even its wounds.*
`;

  /* README.md */
  files["README.md"] = `# ${app.metadata.name}

> *"${app.readme.originStory}"*

${app.metadata.isMeta ? `🌀 **This is a META-APP** - it generates APPs.\n` : ""}

## Quick Start

${app.readme.quickStart}

## Governance: Advice & Consent

This project follows **circulari.ty governance** - consent-based, not top-down:

> *"Governance by advice and a consensus of consent"*

**The Pattern** (inspired by Sociocracy 3.0, Enspiral, Loomio):

1. **Propose**: Share idea freely (RFC, IDEA, proposal)
2. **Seek advice**: Gather input from affected parties
3. **Address concerns**: No objection goes unheard
4. **Consent**: Proceed when no reasoned objections remain

**Not majority rule. Not authority. Consent.**

**Key principle**: *"Good enough for now, safe enough to try"* - iterate rather than perfect.

**Solarpunk roots**: karrot.world, Sociocracy 3.0 (sociocracy30.org), Enspiral, Loomio.

> *"How we decide how we decide."*

## Origin

${app.readme.originStory}

---

*Created ${app.metadata.createdAt.toISOString()} with kimprint*
`;

  return files;
}

/**
 * Generate APP and write to filesystem.
 */
export async function generateAndWriteApp(
  config: AppGenerationConfig,
  outputDir: string
): Promise<string[]> {
  /* Generate the APP */
  const app = generateApp(config);
  
  /* Render to files */
  const files = renderAppToFiles(app);
  
  /* Create output directory */
  await fs.mkdir(outputDir, { recursive: true });
  
  /* Write all files */
  const written: string[] = [];
  for (const [filename, content] of Object.entries(files)) {
    const filepath = path.join(outputDir, filename);
    await fs.writeFile(filepath, content, "utf-8");
    written.push(filepath);
  }
  
  return written;
}

/**
 * List available templates.
 */
export function listTemplates(): Array<{ name: string; description: string }> {
  return [
    { name: "mcp-server", description: "MCP server with stdio transport (like kimprint)" },
    { name: "rust-crate", description: "Rust crate for o19/crates/" },
    { name: "typescript-package", description: "TypeScript package for packages/" },
    { name: "skill", description: "Kimi skill for .kimi/skills/" },
    { name: "custom", description: "Blank slate with structure" },
  ];
}
