/**
 * APP Templates
 * 
 * Templates for generating Action Plan Packages.
 */

import type { AppPackage, AppGenerationConfig } from "./types.js";

/**
 * Generate phases for MCP server template.
 */
function generateMcpServerPhases(config: AppGenerationConfig): AppPackage["execution"]["phases"] {
  return [
    {
      name: "Phase 0: Bootstrap & Understanding",
      description: "Re-ground in context and understand the goal",
      estimatedMinutes: 15,
      steps: [
        { description: `Invoke ${config.skills.join(", ")} skills`, completed: false },
        { description: "Read this entire APP before writing code", completed: false },
        { description: "Verify project structure", completed: false },
      ],
      checkpoints: ["Skills invoked", "APP understood"],
    },
    {
      name: "Phase 1: Project Scaffold",
      description: "Create package structure and initialize",
      estimatedMinutes: 30,
      steps: [
        { description: "Create directory structure", completed: false },
        { description: "Initialize package manager", completed: false },
        { description: "Install MCP SDK and dependencies", completed: false },
        { description: "Configure TypeScript", completed: false },
      ],
      checkpoints: ["Build succeeds", "MCP types available"],
    },
    {
      name: "Phase 2: MCP Server Core",
      description: "Implement MCP server with stdio transport",
      estimatedMinutes: 45,
      steps: [
        { description: "Create server scaffold", completed: false },
        { description: "Register tool handlers", completed: false },
        { description: "Implement conservation tools", completed: false },
        { description: "Test with MCP inspector", completed: false },
      ],
      checkpoints: ["Server starts", "Tools respond"],
    },
    {
      name: "Phase 3: Documentation",
      description: "Write README and architecture docs",
      estimatedMinutes: 20,
      steps: [
        { description: "Write origin story", completed: false },
        { description: "Document architecture", completed: false },
        { description: "Add usage examples", completed: false },
      ],
      checkpoints: ["README complete", "Architecture documented"],
    },
  ];
}

/**
 * Generate architecture for MCP server.
 */
function generateMcpArchitecture(config: AppGenerationConfig): AppPackage["architecture"] {
  return {
    overview: `${config.projectName} is a Model Context Protocol server that provides ${config.description}.`,
    patterns: [
      {
        name: "MCP Protocol",
        description: "Stdio transport for CLI integration",
        rationale: "Standard protocol enables interoperability with any MCP client",
      },
      {
        name: "Tool-based Interface",
        description: "Actions exposed as MCP tools",
        rationale: "Clear contract, discoverable, type-safe",
      },
    ],
    extensionPoints: [
      "Add new tools by extending the tool handler",
      "Add resources for state exposure",
      "Implement custom transports",
    ],
  };
}

/**
 * Generate failure modes for MCP server.
 */
function generateMcpFailureModes(): AppPackage["failureModes"] {
  return {
    risks: [
      {
        scenario: "Tool name contains invalid characters (/, :, etc.)",
        probability: "high",
        impact: "high",
        mitigation: "Use only [a-zA-Z0-9_-] in tool names",
      },
      {
        scenario: "Stdio protocol corruption",
        probability: "medium",
        impact: "high",
        mitigation: "Log to stderr only, stdout is for MCP",
      },
      {
        scenario: "Server crashes on invalid input",
        probability: "medium",
        impact: "medium",
        mitigation: "Validate all inputs with Zod schemas",
      },
    ],
  };
}

/**
 * Generate README content.
 */
function generateReadme(config: AppGenerationConfig): AppPackage["readme"] {
  const metaNote = config.isMeta
    ? "This APP is META - it generates APPs. The spiral conserves its own structure."
    : undefined;

  return {
    originStory: `${config.projectName} was created to ${config.description}. Generated by kimprint.`,
    quickStart: `
## Quick Start

\`\`\`bash
# Install dependencies
npm install

# Build
npm run build

# Start MCP server
npm start
\`\`\`
    `.trim(),
    metaNote,
  };
}

/**
 * Generate APP from template.
 */
export function generateApp(config: AppGenerationConfig): AppPackage {
  const now = new Date();
  
  let phases: AppPackage["execution"]["phases"];
  let architecture: AppPackage["architecture"];
  let failureModes: AppPackage["failureModes"];
  
  switch (config.template) {
    case "mcp-server":
      phases = generateMcpServerPhases(config);
      architecture = generateMcpArchitecture(config);
      failureModes = generateMcpFailureModes();
      break;
    
    default:
      /* Custom template - minimal structure */
      phases = [{
        name: "Phase 1: Setup",
        description: "Initialize project",
        estimatedMinutes: 30,
        steps: [{ description: "Create structure", completed: false }],
        checkpoints: ["Ready for development"],
      }];
      architecture = {
        overview: config.description,
        patterns: [],
        extensionPoints: [],
      };
      failureModes = { risks: [] };
  }
  
  return {
    metadata: {
      name: config.projectName,
      description: config.description,
      version: "0.1.0",
      createdAt: now,
      template: config.template,
      isMeta: config.isMeta,
    },
    skills: config.skills.map(skill => ({
      skill,
      phase: "Phase 0",
      purpose: `Re-ground in ${skill} context`,
    })),
    execution: { phases },
    architecture,
    failureModes,
    readme: generateReadme(config),
  };
}
